# -*- coding: utf-8 -*-
"""Untitled58.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q05hUZB4otICYG_rETttXcqzHyUahmU7
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import solve_continuous_are, inv


A = np.array([[-2.8, 1.5],
              [0.0, -1.2]])
B_u = np.array([[0], [10.0]])
B_w = np.array([[ -0.5], [0]]) # Disturbance: Load Current Transient
C = np.array([[1, 0]])         # Output: Oxygen Partial Pressure


Q = np.diag([500, 10])         # Penalty on Pressure error vs Speed effort
R = np.array([[1.0]])
gamma = 1.5                    # Performance bound (The "Robustness" dial)

def solve_h_inf(A, Bu, Bw, Q, R, gamma):

    H_inf_dist = (1.0 / gamma**2) * (B_w @ B_w.T)
    H_inf_ctrl = Bu @ inv(R) @ Bu.T
    modified_brk = H_inf_dist - H_inf_ctrl
    P = solve_continuous_are(A, np.eye(2), Q, -modified_brk)
    K = inv(R) @ Bu.T @ P
    return K, P

k_rob, _ = solve_h_inf(A, B_u, B_w, Q, R, gamma)


dt, t_end = 0.01, 10.0
t_span = np.arange(0, t_end, dt)
x = np.array([[2000.0], [500.0]])
x_hist, u_hist, dist_hist = [], [], []

for t in t_span:

    dist = 50.0 if 3.0 < t < 7.0 else 0.0


    u = -k_rob @ (x - np.array([[2000.0], [500.0]]))
    u = np.clip(u, 0, 100)


    uncertainty = 1.2
    dx = (A * uncertainty) @ x + B_u @ u + B_w * dist
    x = x + dx * dt

    x_hist.append(x.flatten())
    u_hist.append(u.flatten())
    dist_hist.append(dist)

# --- ANALYTICS & PLOTTING ---
x_hist = np.array(x_hist)
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(t_span, x_hist[:, 0], 'r', lw=2, label='Oxygen Pressure')
plt.axhline(2000, ls='--', color='k', alpha=0.5)
plt.title('Oxygen Starvation Defense'); plt.ylabel('Pressure (Pa)'); plt.legend()
plt.subplot(1, 2, 2)
plt.plot(t_span, u_hist, 'b', label='Compressor Voltage')
plt.title('Robust Actuator Response'); plt.ylabel('Volts'); plt.legend()
plt.tight_layout(); plt.show()

print(f"Optimal H-inf Gain Matrix: {k_rob}")